### ISSUE TITLE
Overscroll

### ISSUE THREAD

**Issue by TheKnarf** [comby-tools/comby.dev#1]
On browser running on Mac, as well as mobil browsers, you can overscroll (aka the pulling down the top motion on mobile). This leads to an artefact where you have some extra white on the top (or the bottom, as you can also overscroll downward).

![Screenshot 2019-09-25 at 10 04 41](https://user-images.githubusercontent.com/213777/65581574-025b7e00-df7c-11e9-8aa8-d972e8e04fa2.png)

Luckily this is trivial to fix! Simply set the background color for the `html` tag:

```
html {
    body: black;
}
```

You can read more about it at: https://peter.coffee/htmls-background-color

**Comment by rvantonder** [comment]
Oooh, thanks for catching. Done in 07ae6041e3ead0f7f79ec670803ea3a45171988b
